# Generated by Django 5.0.6 on 2024-06-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_attribute_attributevalue_alter_image_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
